apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-generator
  labels:
    app: logger
spec:
  replicas: 2
  selector:
    matchLabels:
      app: log
  template:
    metadata:
      labels:
        app: log
    spec:
      containers:
      - name: logx
        image: busybox
        args: [/bin/sh, -c, 'i=0; while true; do echo "$i: Hello Kubevision! The time is $(date)"; i=$((i+1)); sleep 1; done']
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: complex-app
  labels:
    tier: frontend
    env: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-complex
  template:
    metadata:
      labels:
        app: nginx-complex
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: pod
metadata:
  name: crash-test
spec:
  containers:
  - name: crasher
    image: busybox
    command: ["/bin/sh", "-c", "sleep 5; exit 1"]
  restartPolicy: Always

