apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pizzas.food.example.com
spec:
  group: food.example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                toppings:
                  type: array
                  items:
                    type: string
                price:
                  type: integer
      # THIS IS THE MAGIC: Server-Side Columns
      additionalPrinterColumns:
        - name: Price
          type: integer
          jsonPath: .spec.price
        - name: Toppings
          type: string
          jsonPath: .spec.toppings
  scope: Namespaced
  names:
    plural: pizzas
    singular: pizza
    kind: Pizza
    shortNames:
    - pz
---
apiVersion: food.example.com/v1
kind: Pizza
metadata:
  name: vegpizza
spec:
  price: 20
  toppings: ["veggies", "cheese"]
---
apiVersion: food.example.com/v1
kind: Pizza
metadata:
  name: paneerpizza
spec:
  price: 25
  toppings: ["cheese", "paneer"]
