apiVersion: v1
kind: ConfigMap
metadata:
  name: xray-config
  namespace: default
data:
  player_mode: "hardcore"
---
apiVersion: v1
kind: Secret
metadata:
  name: xray-secret
  namespace: default
type: Opaque
data:
  # "secret" base64 encoded
  api-key: ZWZnaGK=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xray-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: xray
  template:
    metadata:
      labels:
        app: xray
    spec:
      containers:
      - name: main
        image: nginx:alpine
        # 1. Test Env Injection
        env:
        - name: GAME_MODE
          valueFrom:
            configMapKeyRef:
              name: xray-config
              key: player_mode
        # 2. Test Volume Mounts
        volumeMounts:
        - name: secret-vol
          mountPath: /etc/secret
      volumes:
      - name: secret-vol
        secret:
          secretName: xray-secret
---
apiVersion: v1
kind: Service
metadata:
  name: xray-service
  namespace: default
spec:
  selector:
    app: xray
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
